# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd9448e2200e2053d10937612191f2f1b142e51eddee6543be4f9063a36566438d3d45e42496bfcf60e6e52446f9fad54f70eb273203c65d3d7b45497088a995

test:
  secret_key_base: 9763276c3b37028f7af0c036e7c8e12df3f6e8db2c0456a41389f0279754089c86f67e586824e41da0164959051990f16a43a177ead21aeea265eb27301dcd0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
